"""QueryExpander: Expand queries using entity links.

Expands query triples by finding similar entities for subject and object,
generating cross-product patterns, and computing combined confidence scores.
"""

from dataclasses import dataclass, field
from typing import Optional

from z3adapter.ikr.entities.schema import Entity
from z3adapter.ikr.entities.store import EntityStore
from z3adapter.ikr.triples.schema import Predicate, PREDICATE_OPPOSITES


# Predicate similarity groups - predicates within each group are semantically related
PREDICATE_SIMILARITY: dict[Predicate, list[tuple[Predicate, float]]] = {
    Predicate.CAUSES: [
        (Predicate.RELATED_TO, 0.5),  # Weaker causal implication
    ],
    Predicate.PREVENTS: [
        (Predicate.RELATED_TO, 0.5),
    ],
    Predicate.IS_A: [
        (Predicate.RELATED_TO, 0.4),
    ],
    Predicate.PART_OF: [
        (Predicate.RELATED_TO, 0.4),
        (Predicate.HAS, 0.6),  # Inverse relationship
    ],
    Predicate.HAS: [
        (Predicate.RELATED_TO, 0.4),
        (Predicate.PART_OF, 0.6),  # Inverse relationship
    ],
    Predicate.BELIEVES: [
        (Predicate.RELATED_TO, 0.3),
    ],
    Predicate.RELATED_TO: [],  # Most generic, no further expansion
}


@dataclass
class ExpandedPattern:
    """A query pattern generated by expanding entity links.

    Represents one possible match pattern with confidence decay
    from the original query based on entity similarity scores.

    Attributes:
        subject_id: Entity ID for subject
        subject_name: Entity name for subject (for display)
        predicate: Predicate (possibly expanded from original)
        object_id: Entity ID for object
        object_name: Entity name for object (for display)
        confidence: Combined confidence from link scores [0, 1]
        subject_score: Similarity score for subject expansion
        object_score: Similarity score for object expansion
        predicate_score: Similarity score for predicate expansion
        is_original: Whether this is the original query pattern

    Example:
        # Original query: (anxiety, causes, memory)
        ExpandedPattern(
            subject_id="e1",
            subject_name="anxiety",
            predicate=Predicate.CAUSES,
            object_id="e2",
            object_name="memory",
            confidence=1.0,
            is_original=True,
        )

        # Expanded: (stress, causes, working_memory)
        ExpandedPattern(
            subject_id="e3",
            subject_name="stress",
            predicate=Predicate.CAUSES,
            object_id="e4",
            object_name="working_memory",
            confidence=0.64,  # 0.8 * 0.8
            subject_score=0.8,
            object_score=0.8,
        )
    """

    subject_id: str
    subject_name: str
    predicate: Predicate
    object_id: str
    object_name: str
    confidence: float

    # Component scores for explainability
    subject_score: float = 1.0
    object_score: float = 1.0
    predicate_score: float = 1.0

    # Flag for original query
    is_original: bool = False


@dataclass
class QueryTriple:
    """A query triple to expand.

    Represents the user's query in entity-linked form.

    Attributes:
        subject_id: Entity ID for subject
        subject_name: Entity name for subject
        predicate: Query predicate
        object_id: Entity ID for object
        object_name: Entity name for object
    """

    subject_id: str
    subject_name: str
    predicate: Predicate
    object_id: str
    object_name: str


class QueryExpander:
    """Expand queries using entity links.

    Takes a query triple and expands it into multiple patterns by:
    1. Finding entities similar to the subject
    2. Finding entities similar to the object
    3. Optionally expanding predicates to similar predicates
    4. Generating cross-product of all expansions
    5. Computing combined confidence for each pattern

    The expanded patterns can then be matched against a knowledge base
    to find relevant evidence even when exact matches don't exist.

    Example:
        store = EntityStore("knowledge.db")
        expander = QueryExpander(store, min_score=0.5, max_expansions=20)

        query = QueryTriple(
            subject_id="e1",
            subject_name="anxiety",
            predicate=Predicate.CAUSES,
            object_id="e2",
            object_name="memory_problems",
        )

        patterns = expander.expand(query)
        # Returns patterns like:
        #   (anxiety, causes, memory_problems)    conf=1.0
        #   (anxiety, causes, memory)             conf=0.9
        #   (stress, causes, memory_problems)     conf=0.85
        #   (stress, causes, memory)              conf=0.77
        #   ...
    """

    def __init__(
        self,
        entity_store: EntityStore,
        min_score: float = 0.5,
        max_expansions: int = 20,
        expand_predicates: bool = False,
    ):
        """Initialize QueryExpander.

        Args:
            entity_store: EntityStore for looking up similar entities
            min_score: Minimum confidence score for expanded patterns
            max_expansions: Maximum number of patterns to return
            expand_predicates: Whether to expand predicates to similar ones
        """
        self.entity_store = entity_store
        self.min_score = min_score
        self.max_expansions = max_expansions
        self.expand_predicates = expand_predicates

    def expand(self, query: QueryTriple) -> list[ExpandedPattern]:
        """Expand a query triple into multiple patterns.

        Args:
            query: Query triple to expand

        Returns:
            List of ExpandedPattern sorted by confidence descending,
            limited to max_expansions
        """
        # Get subject expansions (including original with score 1.0)
        subject_expansions = self._get_entity_expansions(
            query.subject_id, query.subject_name
        )

        # Get object expansions (including original with score 1.0)
        object_expansions = self._get_entity_expansions(
            query.object_id, query.object_name
        )

        # Get predicate expansions (including original with score 1.0)
        predicate_expansions = self._get_predicate_expansions(query.predicate)

        # Generate cross-product of all expansions
        patterns: list[ExpandedPattern] = []

        for subj_id, subj_name, subj_score in subject_expansions:
            for obj_id, obj_name, obj_score in object_expansions:
                for pred, pred_score in predicate_expansions:
                    combined = subj_score * obj_score * pred_score

                    if combined >= self.min_score:
                        is_original = (
                            subj_id == query.subject_id
                            and obj_id == query.object_id
                            and pred == query.predicate
                        )

                        patterns.append(
                            ExpandedPattern(
                                subject_id=subj_id,
                                subject_name=subj_name,
                                predicate=pred,
                                object_id=obj_id,
                                object_name=obj_name,
                                confidence=combined,
                                subject_score=subj_score,
                                object_score=obj_score,
                                predicate_score=pred_score,
                                is_original=is_original,
                            )
                        )

        # Sort by confidence descending
        patterns.sort(key=lambda p: (-p.confidence, p.is_original))

        # Limit to max_expansions
        return patterns[: self.max_expansions]

    def _get_entity_expansions(
        self, entity_id: str, entity_name: str
    ) -> list[tuple[str, str, float]]:
        """Get entity and its similar entities.

        Args:
            entity_id: Entity ID
            entity_name: Entity name

        Returns:
            List of (entity_id, entity_name, score) tuples.
            Original entity is always first with score 1.0.
        """
        # Start with original entity
        expansions = [(entity_id, entity_name, 1.0)]

        # Get similar entities from store
        similar = self.entity_store.get_similar(
            entity_id, min_score=self.min_score, limit=self.max_expansions
        )

        for entity, score in similar:
            expansions.append((entity.id, entity.name, score))

        return expansions

    def _get_predicate_expansions(
        self, predicate: Predicate
    ) -> list[tuple[Predicate, float]]:
        """Get predicate and its similar predicates.

        Args:
            predicate: Original predicate

        Returns:
            List of (predicate, score) tuples.
            Original predicate is always first with score 1.0.
        """
        # Start with original predicate
        expansions = [(predicate, 1.0)]

        # Add similar predicates if enabled
        if self.expand_predicates:
            similar = PREDICATE_SIMILARITY.get(predicate, [])
            for similar_pred, score in similar:
                if score >= self.min_score:
                    expansions.append((similar_pred, score))

        return expansions

    def expand_by_name(
        self,
        subject: str,
        predicate: Predicate,
        obj: str,
        subject_type: Optional[str] = None,
        object_type: Optional[str] = None,
    ) -> list[ExpandedPattern]:
        """Expand a query by entity names (convenience method).

        Looks up or creates entities by name, then expands.

        Args:
            subject: Subject entity name
            predicate: Query predicate
            obj: Object entity name
            subject_type: Optional entity type for subject
            object_type: Optional entity type for object

        Returns:
            List of ExpandedPattern sorted by confidence
        """
        # Get or create subject entity
        subject_entity, _ = self.entity_store.get_or_create(
            subject, entity_type=subject_type
        )

        # Get or create object entity
        object_entity, _ = self.entity_store.get_or_create(
            obj, entity_type=object_type
        )

        # Create query triple
        query = QueryTriple(
            subject_id=subject_entity.id,
            subject_name=subject_entity.name,
            predicate=predicate,
            object_id=object_entity.id,
            object_name=object_entity.name,
        )

        return self.expand(query)

    def get_opposite_patterns(
        self, patterns: list[ExpandedPattern]
    ) -> list[ExpandedPattern]:
        """Generate opposite predicate patterns for contradiction detection.

        For each pattern with an opposite predicate (e.g., causes/prevents),
        generates a pattern with the opposite predicate.

        Args:
            patterns: List of expanded patterns

        Returns:
            List of patterns with opposite predicates
        """
        opposite_patterns = []

        for pattern in patterns:
            opposite_pred = PREDICATE_OPPOSITES.get(pattern.predicate)
            if opposite_pred:
                opposite_patterns.append(
                    ExpandedPattern(
                        subject_id=pattern.subject_id,
                        subject_name=pattern.subject_name,
                        predicate=opposite_pred,
                        object_id=pattern.object_id,
                        object_name=pattern.object_name,
                        confidence=pattern.confidence,
                        subject_score=pattern.subject_score,
                        object_score=pattern.object_score,
                        predicate_score=pattern.predicate_score,
                        is_original=False,
                    )
                )

        return opposite_patterns
